/* Formatted on 11/27/2022 10:51:21 AM (QP5 v5.115.810.9015) */
CREATE OR REPLACE TRIGGER INS."TRG_ACC_COLL_SUMMERY_DEL_LOG"
   BEFORE DELETE OR UPDATE
   ON ins.ACC_COLL_SUMMERY
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
   /******************************************************************************
   NAME:       TRG_ACC_COLL_SUMMERY_DEL_LOG
  PURPOSE: TO store  data for tracing which are deleted or updated.

   REVISIONS:
   Ver        Date          Author                    Description
   ---------  -----------  ------------------------  --------------------------
   1.0        27-NOV-2022  1.Md. Alamgir Hossain Created this trigger.

   NOTES:
   If Any update or delete operation perform on  ACC_COLL_SUMMERY then
   old information is inserted into  ACC_COLL_SUMMERY_DELETE_LOG
******************************************************************************/
DECLARE
BEGIN
   INSERT INTO ACC_COLL_SUMMERY_DELETE_LOG (RECEIVE_ID,
                                            PGID,
                                            COLL_FROM,
                                            INSTALLMENT_NO,
                                            ACTIVE_OFFICE_CD,
                                            ACTIVE_BRANCH_CD,
                                            ACTIVE_SALES_CD,
                                            ACTIVE_ZONAL_CD,
                                            ACTIVE_REGIONAL_CD,
                                            OFFICE_CODE,
                                            RECEIVE_DT,
                                            AMOUNT_TYPE,
                                            STATUS,
                                            COLLECTION_TYPE,
                                            RECEIVE_MODE,
                                            PROCESS_DATE,
                                            FIRST_PREM,
                                            DEFFERED,
                                            SECOND_YR,
                                            RENEWAL,
                                            LATE_FEE,
                                            SUSPENSE_AMT,
                                            F_COLL_AMOUNT,
                                            D_COLL_AMOUNT,
                                            S_COLL_AMOUNT,
                                            R_COLL_AMOUNT,
                                            AVL_SUS_AMT,
                                            DUE_DATE,
                                            BUSINESS_YR,
                                            BRANCH_OFF,
                                            SALES_OFF,
                                            ZONAL_OFF,
                                            REGIONAL_OFF,
                                            SERVICING_OFF,
                                            CHEQUE_NO,
                                            TO_BANK_CD,
                                            TO_BR_CD,
                                            U_DATE,
                                            BUSINESS_DATE,
                                            AGENT_ID,
                                            UM_GID,
                                            BM_GID,
                                            BC_GID,
                                            DC_GID,
                                            RC_GID,
                                            DVC_GID,
                                            CC_GID,
                                            INS_TP_CD,
                                            REC_STATUS,
                                            PROJECT_CD,
                                            POLICY_FILE_TP,
                                            COLL_FROM_DEPT,
                                            COM_BILL_DATE,
                                            COM_EXE_DATE,
                                            AGM_GID,
                                            DGM_GID,
                                            GM_GID)
     VALUES   (:OLD.RECEIVE_ID,
               :OLD.PGID,
               :OLD.COLL_FROM,
               :OLD.INSTALLMENT_NO,
               :OLD.ACTIVE_OFFICE_CD,
               :OLD.ACTIVE_BRANCH_CD,
               :OLD.ACTIVE_SALES_CD,
               :OLD.ACTIVE_ZONAL_CD,
               :OLD.ACTIVE_REGIONAL_CD,
               :OLD.OFFICE_CODE,
               :OLD.RECEIVE_DT,
               :OLD.AMOUNT_TYPE,
               :OLD.STATUS,
               :OLD.COLLECTION_TYPE,
               :OLD.RECEIVE_MODE,
               :OLD.PROCESS_DATE,
               :OLD.FIRST_PREM,
               :OLD.DEFFERED,
               :OLD.SECOND_YR,
               :OLD.RENEWAL,
               :OLD.LATE_FEE,
               :OLD.SUSPENSE_AMT,
               :OLD.F_COLL_AMOUNT,
               :OLD.D_COLL_AMOUNT,
               :OLD.S_COLL_AMOUNT,
               :OLD.R_COLL_AMOUNT,
               :OLD.AVL_SUS_AMT,
               :OLD.DUE_DATE,
               :OLD.BUSINESS_YR,
               :OLD.BRANCH_OFF,
               :OLD.SALES_OFF,
               :OLD.ZONAL_OFF,
               :OLD.REGIONAL_OFF,
               :OLD.SERVICING_OFF,
               :OLD.CHEQUE_NO,
               :OLD.TO_BANK_CD,
               :OLD.TO_BR_CD,
               :OLD.U_DATE,
               :OLD.BUSINESS_DATE,
               :OLD.AGENT_ID,
               :OLD.UM_GID,
               :OLD.BM_GID,
               :OLD.BC_GID,
               :OLD.DC_GID,
               :OLD.RC_GID,
               :OLD.DVC_GID,
               :OLD.CC_GID,
               :OLD.INS_TP_CD,
               :OLD.REC_STATUS,
               :OLD.PROJECT_CD,
               :OLD.POLICY_FILE_TP,
               :OLD.COLL_FROM_DEPT,
               :OLD.COM_BILL_DATE,
               :OLD.COM_EXE_DATE,
               :OLD.AGM_GID,
               :OLD.DGM_GID,
               :OLD.GM_GID);
END TRG_ACC_COLL_SUMMERY_DEL_LOG;
/